### ISSUE TITLE
Add PATCH

### ISSUE THREAD

**Issue by ribomation** [ggalmazor/jfry#14]
Just noticed http operation PATCH is not supported. I'm using it to partially update resources.

**Comment by ggalmazor** [comment]
Ok, I need to write a specific integration test for that as it's not a standard method in HTTP1.1 specification. I've already checked that Jetty won't complain but we need to be sure that future server adapters work well with it as well.

**Comment by ggalmazor** [comment]
Implemented PATCH method in version 0.0.18
